---
name: Access to Copilot
description: Request access to Copilot
title: "Access to Copilot"

body:
- type: markdown
  attributes:
    value: >
      **Please hit submit to gain access to Copilot**


- type: input
  attributes:
    label: Netapp Email 
    description: >
      What is your netapp email?
    placeholder: ontap@netapp.com
  validations:
    required: true
