---
name: Access to Copilot
description: Request access to Copilot for new and returning users
title: "Access to Copilot"

body:
- type: markdown
  attributes:
    value: >
      Getting access to Copilot is easy! Just fill out the form below and we'll get you set up in no time. 
      Please fill in your username below, read over the GenAI Guidance, and submit your request with the green button at the bottom of the page.


- type: input
  attributes:
    label: Netapp Username 
    description: >
      What is your NetApp username? Make sure to use your NetApp unix username (carchi) and not your github username or Netapp Email address.
    placeholder: carchi
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      # Set Up
      Please review the setup instruction [here on confluence](https://confluence.ngage.netapp.com/display/NGAGE/Copilot)

      # Where Can I Use Copilot for NetApp Development?

      GitHub Copilot users must adhere to the guidelines for Generative AI outlined in the legal department's [GenAI Guidance](https://netapp.sharepoint.com/:w:/r/sites/LegalCentral/_layouts/15/Doc.aspx?sourcedoc=%7B953E5610-67F6-4AFC-AF5F-9C27D20EA37A%7D&file=GenAI%20Preliminary%20Guidance.docx&action=default&mobileredirect=true).

      For more product-specific acceptable use cases, refer to the following link: [Additional product-based acceptable use cases:](https://confluence.ngage.netapp.com/display/TPP/Acceptable+GenAI+Use+Cases+for+product+code).

      Always check the documentation for updates, as it may become more permissive over time. As of March 5, 2024, the guidance is as follows:

      ## For Internal Infrastructure and Services in NetApp Engineering:

      You may use approved secure sandboxes designated for internal infrastructure and services for any use case.

      ## For Product Development (All Other Cases):

      You may use approved secure sandboxes intended for product development for the following internal use cases:

      - Knowledge search/chat (note: copying of output is not permitted).
      - Unit testing, test automation, and test infrastructure (please ensure that this test code is not distributed as part of any source or binary code for any product or service). Test code may be checked into the same repository as the product code. While test code can be distributed, it must remain independent of the product.
      - Code comments that are visible only within NetApp may be added directly to product source files, as long as these comments do not ship to customers (for example, comments can be compiled out during the product creation process).
      - Log and failure analyses.
      - Bug identification.
