name: Check Open Tickets and Notify Slack

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python gh_workflows/check_tickets.py
        env:
          GH_AUDIT: ${{ secrets.ADMIN_GITHUB_TOKEN }}