name: Github username to Netapp Email mappings

on:
  schedule:
    - cron: '30 3 * * * '
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Python script
      run: python3 gh_workflows/github_netapp_mapping.py
      env:
        GH_AUDIT: ${{ secrets.GH_AUDIT }}
