name: Add user to org

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: ubuntu-latest
    steps:

      - name: Check if user is a member of the organization
        id: check_membership
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/members/{username}
          org: Netapp-Copilot
          username: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        continue-on-error: true
        
      - name: Add user to organization
        if: steps.check_membership.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/{org}/memberships/{username}
          org: Netapp-Copilot
          username: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Welcome user
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hello @${{ github.actor }}, please make sure to add your self to ng-github-users using the [Netapp Group Management tool](https://nag.netapp.com/). Do note it can take about 1 to 2 hours for the Netapp Group Management tool to add you to the Azure login group. If you have issues with the tool please reach out to helpdesk@netapp.com.

            Once you've been added to the NG group. You will receive an email from Github letting you know you now have access to Copilot. This ticket will also get updated letting you now have access to copilot. If you have any questions please reach out to ng-github-admins@netapp.com
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
