name: Add user to org

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: self-hosted
    steps:
      
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if user is a member of the organization
        id: check_membership
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/members/{username}
          org: Netapp-Copilot
          username: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_AUDIT }}
        continue-on-error: true

      - name: Check if user exist in Netapp Enterprise
        id: check_netapp_user
        env:
          ADMIN_AUDIT: "${{ secrets.ADMIN_AUDIT }}"
        run: |
          python3 gh_workflows/check_existing.py --token "$ADMIN_AUDIT" --username "${{ github.event.issue.user.login }}"
        continue-on-error: true


      - name: Get Netapp Username
        id: get_netapp_username  # Add an ID to reference this step
        env:
          ADMIN_AUDIT: "${{ secrets.ADMIN_AUDIT }}"
        run: |
                username=$(python3 gh_workflows/get_username.py --issue_number "${{ github.event.issue.number }}")
                echo "::set-output name=netapp_username::$username"
        continue-on-error: true

      - name: Add label based on membership status
        if: steps.check_membership.outcome == 'failure'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: new_users
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Add label for existing user
        if: steps.check_membership.outcome == 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: existing_user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check usernames
        if: steps.get_netapp_username.outputs.netapp_username == github.event.issue.user.login
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.actor }}, it appears that your NetApp username and GitHub username are the same. Please double-check that you’ve entered your NetApp username correctly. If you find that you entered the wrong username, kindly close this issue and open a new one with the correct username.
            If both usernames are indeed the same, please reach out to ng-github-users for assistance.
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Exit if usernames match
        if: steps.get_netapp_username.outputs.netapp_username == github.event.issue.user.login
        run: exit 1
      # New user logic (These are user who are not in the org and not part of the Enterprise so do not have a Netapp email address). They need to be added to the NG (which takes an hour  to sync) and then added to the org.
      # a section action (check_user) will continue their request to be added to the org.

      - name: New Users
        if: steps.check_membership.outcome == 'failure' && steps.check_netapp_user.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hi @${{ github.actor }}, welcome to Copilot!!!

            As a new user, please ensure that your NetApp email address <username>@netapp.com is listed among your emails here: https://github.com/settings/emails. If it is not, you will encounter an SSO error when logging in.
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Add users to NG
        if: steps.check_membership.outcome == 'failure' && steps.check_netapp_user.outcome == 'failure'
        env:
          TENANT_ID: "${{ secrets.TENANT_ID }}"
          CLIENT_ID: "${{ secrets.CLIENT_ID }}"
          SCOPE: "${{ secrets.SCOPE }}"
          CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
        run: |
          python3 gh_workflows/add_to_ng.py --username "${{ steps.get_netapp_username.outputs.netapp_username }}"

      - name: tell user they have been added to NG
        if: steps.check_membership.outcome == 'failure' && steps.check_netapp_user.outcome == 'failure'
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hi @${{ github.actor }},

            You have been added to the ng-github-user group. In approximately one hour, you will receive an invitation email from GitHub to join the Netapp-Copilot organization. The email will be sent from noreply@github.com.

            Please make sure to accept the invitation in order to gain access to Copilot. If you don’t see the email, kindly check your junk mail folder. Once you accept the invitation, you will have access to Copilot.

            If you cannot find the email, you can also go to https://github.com/Netapp-Copilot to accept the invitation directly.

            Remember, you need to accept the invitation to receive a license for Copilot.

            Thank you!

      # these are existing user who have been deactivated and need to be reactivated (As they are part of the enterprise they do not need to be added to the NG, and can be instance reactivated


      - name: Check if User is in Active Group
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success'
        id: check_active_group
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/teams/{team_slug}/memberships/{username}
          org: Netapp-Copilot  # Replace with your GitHub organization
          team_slug: 8276605  # The slug of the team
          username: ${{ github.actor }}  # The username to check
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        continue-on-error: true

      - name: Existing Users
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hi @${{ github.actor }}, welcome back to Copilot!!!
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Add User back to active group
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/{org}/teams/{team_slug}/memberships/{username}
          org: Netapp-Copilot  # Replace with your GitHub organization
          team_slug: active-users  # The slug of the team
          username: ${{ github.actor }}  # The username to add
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      
      - name: Let user know they are added back to active group
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hi @${{ github.actor }}, Your account has been reactivated. You should now have access to Copilot.
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Close the issue
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repo}/issues/{issue_number}
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}


      # these are uses who are already in the org and active, so they don't need to do anything. Ask them to reach out to the admins if they are having issues.

      - name: User already in active group
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'success'
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hey @${{ github.actor }}, You Already have access to Copilot. If your having issues or hitting an error please email ng-github-admins@netapp.com and let us know what the issue is.

      - name: Close the issue
        if: steps.check_membership.outcome == 'success' && steps.check_netapp_user.outcome == 'success' && steps.check_active_group.outcome == 'success'
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{repo}/issues/{issue_number}
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  
      
