name: Print Username

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the username
        run: | 
          USERNAME=$(echo '${{ github.event.issue.user.login }}')
          echo "::set-output name=username::$USERNAME"
      - name: Add user to organization
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/{org}/memberships/{username}
          org: Netapp-Copilot
          username: ${{ steps.extract.outputs.username }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
