name: Print Username

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the username
        run: echo "The username is ${{ github.event.issue.user.login }}"
