name: Add user to org

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: ubuntu-latest
    steps:

      - name: Check if user is a member of the organization
        id: check_membership
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/members/{username}
          org: Netapp-Copilot
          username: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        continue-on-error: true

      - name: New Users
        if: steps.check_membership.outcome == 'failure'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/issues/{issue_number}/comments
          repo: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: >
            Hi @${{ github.actor }}, welcome to Copilot!!!

            As a new user, please make sure your NetApp Email address <username>@netapp.com is listed as one of your emails here. https://github.com/settings/emails. If not, you will receive an SSO error when logging in to join the org.

            In about an hour you will receive an email from GitHub with an invite to the Netapp-copilot org. The email address will be from noreply@github.com You must accept the invite to get access to Copilot. The email may be in your junk mail folder.
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      # TODO: Add user to NG
      
