name: Print Username

on:
  issues:
    types: [opened]

jobs:
  print_username:
    runs-on: ubuntu-latest
    steps:
      - name: Add user to organization
        uses: octokit/request-action@v2.x
        with:
          route: PUT /orgs/{org}/memberships/{username}
          org: YOUR_ORGANIZATION_NAME
          username: ${{ github.event.issue.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
